### PR TITLE
pubsub: pass in Harness rather than Harness maker func in conformance tests

### LINKED ISSUE #1231: pubsub: pass harness into tests instead of making harnesses inside them
This is a bit of refactoring in drivertest.go called for by changes made for awspubsub.

### PR DESCRIPTION
**Pull request by ijt**
Fixes #1231 

Also, this fixes a bug in which TestSendReceiveTwo was being skipped for all providers in replay mode, not just awspubsub.

### CODE REVIEW

**Comment by jba** [comment]
I made this suggestion months ago and it was rejected.

**Comment by ijt** [comment]
It was rejected because supposedly multiple harnesses would be created within the tests but so far we have no evidence of this.

**Comment by jba** [comment]
It was rejected because *blob* creates multiple harnesses, not pubsub. But I guess @vangent should weigh in.

**Comment by ijt** [comment]
I see your point about consistency. I'm closing this to work on something more likely to be useful.

**Pull request closed without merging**
