### PR TITLE
doc: make ref headings consistent with howto headings

### PR DESCRIPTION
**Pull request by eliben**

### CODE REVIEW

**Comment by zombiezen** [comment]
I'm not sure I agree with this change. I think it would be better to have the reference section be titled after the packages each section represents. WDYT?

**Comment by eliben** [comment]
> I'm not sure I agree with this change. I think it would be better to have the reference section be titled after the packages each section represents. WDYT?

They aren't right now, or at least the capitalization is wrong, so it just seems like an inconsistency. An alternative would be to rename the ref headings to be `fixed width` package names, which would give a better clue to their difference from the other sections?

**Comment by zombiezen** [comment]
> An alternative would be to rename the ref headings to be `fixed width` package names, which would give a better clue to their difference from the other sections?

That sounds good. I'd be willing to take a shot at that, if you like. Main thing stopping us is we'd have to poke at the Hugo layout templates to change the sidebar styling.

**Comment by eliben** [comment]
> > An alternative would be to rename the ref headings to be `fixed width` package names, which would give a better clue to their difference from the other sections?
> 
> That sounds good. I'd be willing to take a shot at that, if you like. Main thing stopping us is we'd have to poke at the Hugo layout templates to change the sidebar styling.

Sure, go for it.  I figured it would *just work* but maybe styling tweaks are required too

**Comment by eliben** [comment]
#2430 is a better fix

**Pull request closed without merging**
