### PR TITLE
internal/secrets/driver: Add Crypter interface to group Encrypt() and Decrypt()

### PR DESCRIPTION
**Pull request by clausti**
Updates #781

### CODE REVIEW

**Comment by zombiezen** [comment]
How do you envision this interface being used? I suspect it to be useful for conformance tests, but it would be helpful to have context.

**Comment by vangent** [comment]
Sorry, I took a look at that PR and it's still not obvious to me why `Crypter` is needed. Users should be able to use `Encrypter` and `Decrypter` independently, so why are the conformance tests requiring providers to expose a single unioned type?

**Comment by clausti** [comment]
@vangent I think our rationale was that you kind of can't test decryption without having first encrypted something, but I have also closed the associated PR.

**Comment by vangent** [comment]
> you kind of can't test decryption without having first encrypted something

Yes, that is true. It's hard to imagine writing a conformance test for one of the two interfaces in isolatino. But I don't think that that requirement for testing implies that the driver interface needs to have a unioned interface; the test can just require that the harness provide one of each.

**Pull request closed without merging**
