### PR TITLE
internal/testing: include gocdk CLI module

### PR DESCRIPTION
**Pull request by zombiezen**
Forgot to do this in earlier PRs.

### CODE REVIEW

**Comment by vangent** [comment]
Test is failing: FAIL: dependencies changed; compare listdeps.sh output with alldeps

but basic idea LGTM.

**Comment by zombiezen** [comment]
Curious, since I did already run listdeps.sh: it seems like this discrepancy is coming from the fact that Travis is configured to run Go 1.11, but I thought we all agreed that we should start running Go 1.12. Should I update the Travis config?

**Comment by vangent** [comment]
I would check with jba@. There's #1557 in flight, but it hasn't been touched in a while.

**Comment by zombiezen** [comment]
Ah, that's probably where my confusion's coming from. I'll leave it as-is, hopefully tests should pass now.

**Pull request merged**
