### PR TITLE
tests: run "wire diff" in addition to "wire check"

### LINKED ISSUE #827: all: travis should verify that `go generate` output matches checked-in `wire_gen.go`
Travis should verify that running `go generate` for the Wire injectors in our repo actually produces the checked-in `wire_gen.go`.

### PR DESCRIPTION
**Pull request by vangent**
This ensures that the checked-in `wire_gen.go` files in our repository match what a fresh run of `wire` would generate.

Fixes #827.

### CODE REVIEW

**Comment by zombiezen** [comment]
I would argue that both should be run: `wire check` ensures that any exported provider sets pass analysis, while `wire diff` ensures that the generated code has not drifted.

**Comment by vangent** [comment]
> I would argue that both should be run: `wire check` ensures that any exported provider sets pass analysis, while `wire diff` ensures that the generated code has not drifted.

IIUC, `wire diff` checks the "provider sets pass analysis" too, no? Are there scenarios where `wire.Load` will fail but `wire.Generate` succeeds?

**Comment by zombiezen** [comment]
The roots of `wire.Generate` are any injectors discovered in the named packages. The roots of `wire.Load` are any provider sets found in top-level variable declarations in the named packages. If a provider set is not used in an injector (i.e. a library provider set), then `wire.Generate` will not perform analysis.

**Comment by vangent** [comment]
Ah, I see. OK, restoring `wire check`.

**Pull request merged**
