### PR TITLE
Azure Blob Storage proposal

### PR DESCRIPTION
**Pull request by vsaroopchand**
Here is my proposal for Azure Blob Storage using the latest [SDK](github.com/Azure/azure-storage-blob-go/2018-03-28/azblob)

### CODE REVIEW

**Comment by vsaroopchand** [comment]
Re: CLA - I signed it!

**Comment by vsaroopchand** [comment]
I signed it!

**Comment by vangent** [comment]
Hi @vsaroopchand, thanks for the contribution! We're discussing how to deal with this internally, and will get back to you soon with a review. In the meantime, could you pull in changes from head?

**Comment by vsaroopchand** [comment]
@vangent I pulled in changes from head; if you prefer, I can move my changes into a feature branch and resubmit a pull request.

**Comment by vangent** [comment]
Hi @vsaroopchand, thanks again for the PR, and sorry for the delay!

We’re really appreciative, but at the moment we aren’t ready to accept contributions for an additional provider. We’re actively working on it, but until we're ready, we'd like to wait on incorporating your contribution.

Expect to hear more about next steps from us in the next few weeks.

**Comment by vsaroopchand** [comment]
@vangent Thanks for the feedback; I will monitor #76 for next steps.

**Pull request closed without merging**
