### PR TITLE
runtimevar/etcdvar: drop support for runtimevar/etcd going forward until they fix their go module problems

### PR DESCRIPTION
**Pull request by vangent**
Updates #2914

### CODE REVIEW

**Comment by vangent** [comment]
FYI my plan after this is to update all dependencies again (after dropping etcd, everything upgrades cleanly!), then do a release. Possibly wait for the 2 other pending PRs from contributors.

**Comment by eliben** [comment]
Is there a chance etcd are just going to fix their module snafu soon? (it's not the fist time...)

**Comment by vangent** [comment]
> Is there a chance etcd are just going to fix their module snafu soon? (it's not the fist time...)

Not really. It's been this way since July, and there is no plan or ETA yet.

**Comment by eliben** [comment]
OK, and OOC - do we have to upgrade etcd at all?

**Review by eliben — APPROVED** [review]
LGTM

The questions in the comments are just informational

**Comment by vangent** [comment]
> do we have to upgrade etcd at all

No, and that's what I've done in the past -- just refrained from updating it if the newer versions have problems. However, in this case, etcd's problems prevent us from upgrading other modules (gorpc, and then everything that depends on that, which is all of the GCP modules). That's not OK.

**Pull request merged**
