### PR TITLE
blob: convert gocloud errors in `Open()` into appropriate fs errors

### PR DESCRIPTION
**Pull request by milescrabill**
Motivation:
- `http.ServeFileFS()` uses `errors.Is()` to match on `fs.ErrNotExist` and `fs.ErrPermission` errors and return corresponding HTTP status codes.
- gocloud currently returns `fs.PathError` which do not wrap the underlying `fs` errors, and which are not handled by `http.ServeFileFS()`'s error handling.
- gocloud returning `fs.PathError`s results in `http.ServeFileFS()` serving Internal Server Errors instead of Not Found or Permission Denied errors.

Fix:
- wraps gocloud NotFound and PermissionDenied errors encountered in `Open()` around their `io/fs` counterparts
- does not perform wrapping for other gocloud errors as they can either not occur or are ambiguous in this context

### CODE REVIEW

**Comment by achew22** [comment]
@peczenyj it seems you've had some luck getting things merged into this repo. Do you have any tips or tricks on how to get this one reviewed?

**Comment by vangent** [comment]
Please be patient.

**Comment by peczenyj** [comment]
I had no idea, to be honest. I send the first pull request without any expectations based on my previous attempts to contribute to other google projects. Somehow this project is different, maybe it is more close to the open source community.

Is there any mailing list where you can expose your problem and mention that you have an awesome pull request for that?

If the maintainers do not react with the necessary speed, perhaps you should consider fork the project - if the license allow - and if your fork get some attention maybe it change things (like archive this repo and point yours as the replacement - why not?)

Sometimes I just start pull requests because code can be more direct than discussions. But not all maintainers like this approach, since I can suggest something undesirable or using the wrong design. It can end in frustration. But I try not to be sentimental.

When issues or pull requests have no feedback for some time it give the wrong impression that they just don’t care. But in fact they can be very busy.

In fact I saw, on this project, many small opportunities to contribute and things to improve, etc. I would love continue to send PRs but first I’d to see what I just did being released.

maybe one day I can have a more substantial role, the I can do more than just write random thoughts

**Comment by peczenyj** [comment]
Or we can just ping @vangent and try to bribe him and with some beers

**Review by vangent — APPROVED** [review]

**Pull request merged**
