### PR TITLE
internal/gocdk: use a logger instead of straight fmt.Printf

### PR DESCRIPTION
**Pull request by vangent**

### CODE REVIEW

**Comment by clausti** [comment]
@zombiezen told me not to use a logger on this the first time around?

**Comment by vangent** [comment]
> @zombiezen told me not to use a logger on this the first time around?

Hmm, we appear to be pretty inconsistent. This uses `fmt.Printf`, `init.go` uses `fmt.Fprintf(pctx.stdout, ...`, and `demo.go` uses `logger`. We should be consistent, and it should be easier to be consistent.

BTW, I noticed this because when you run `go test`, this message gets printed out (and nothing else), which doesn't seem right.

Maybe we should add functions to `ProcessContext` for `Log` and `Printf` and use those everywhere?

**Comment by clausti** [comment]
>Maybe we should add functions to ProcessContext for Log and Printf and use those everywhere?

That would definitely make it easier to be consistent.

**Comment by zombiezen** [comment]
See #2038 for my original report (and I've added some more nuance). I'd like to see us address the larger problem rather than trying to optimize individual parts, but I'm happy to approve if this blocks something.

**Comment by vangent** [comment]
> See #2038 for my original report (and I've added some more nuance). I'd like to see us address the larger problem rather than trying to optimize individual parts, but I'm happy to approve if this blocks something.

It doesn't block anything, I just find it annoying to see this one message every time I run tests.

@clausti , up to you whether to go ahead with this or drop it and wait for the larger fix.

**Comment by clausti** [comment]
Yeah, let's go ahead and remove that annoyance

**Pull request merged**
