### PR TITLE
all: update go-cmp to 0.3

### PR DESCRIPTION
**Pull request by zombiezen**
Picks up improvements in diff output

### CODE REVIEW

**Comment by vangent** [comment]
Where are all of the new dependencies in `go.mod` coming from? I don't trust `go mod tidy`.

**Comment by jba** [comment]
Agreed. Can you run some go mod why's, Ross? I'm particularly curious about why there are two different imports for rethinkDB.

**Comment by zombiezen** [comment]
Problems seem to boil down largely to Vault: #1958. I am not confident that this is the entirety of the problem, but it's creating enough noise that it's hard for me to gather more information about where the other go.mod requirements are coming from.

I'll walk back the `go mod tidy` and simply change the version, but I think we should get rid of this haunted graveyard ASAP.

**Comment by eliben** [comment]
> I'll walk back the `go mod tidy` and simply change the version, but I think we should get rid of this haunted graveyard ASAP.

By this do you mean #886 or something else?

**Comment by zombiezen** [comment]
I mean that this PR will simply update the go-cmp dependency with no other changes.

**Pull request merged**
