### PR TITLE
server/requestlog: Add Request Context in requestlog.Entry

### PR DESCRIPTION
**Pull request by mickeyreiss**
I would like to have access to the request's Context in the request logger, so that I can include metadata and also reference logging implementation details that might be stashed away in the context.

This is particularly useful for request loggers that aim to perform tracing with frameworks other than opencensus. It's also helpful for integrating with certain logging frameworks. I've also noticed that it is a good way to pass information from the `http.Server`s (e.g. [`BaseContext`](https://github.com/golang/go/blob/87c6fa4f473f178f7d931ddadd10c76444f8dc7b/src/net/http/server.go#L2627-L2638)) down to the request logger.

To solve this, I've added a new field to `Entry` that is set based on the context from the request. I believe this change is relatively simple and backwards compatible.

### CODE REVIEW

**Comment by mickeyreiss** [comment]
I am not familiar with the test frameworks in this library. If this is PR is looking good, I would be happy to add a line of code somewhere to maintain the test coverage.

**Comment by vangent** [comment]
@zombiezen thoughts?

Add a context.Context to a struct is generally discouraged:
https://blog.golang.org/context-and-structs

**Comment by mickeyreiss** [comment]
> Add a context.Context to a struct is generally discouraged:
> https://blog.golang.org/context-and-structs

Fair enough, I generally agree. I did it this way based on the `Exception to the rule: preserving backwards compatibility` recommendation in that blog post. Is there different design that will work with the `Logger` interface?

**Comment by jba** [comment]
I think it's okay here, but how about a change that's both more general and less controversial: adding the `Request` to the `Entry`? After all, it is a _request_ logger.

**Comment by mickeyreiss** [comment]
> I think it's okay here, but how about a change that's both more general and less controversial: adding the `Request` to the `Entry`? After all, it is a _request_ logger.

@jba That would solve everything I am looking for. Would you recommend deprecating the redundant fields (`Referer`, `UserAgent`, etc.)? Do you have something in mind for handling the `Body`, which is in an undefined state at this point (depending on whether or not it's been read)?

**Comment by jba** [comment]
You can document the redundant fields as deprecated. Also document that the implementor of Logger shouldn't touch the body.

This is all subject to @vangent's OK, BTW.

**Comment by zombiezen** [comment]
It's been a while, but IIRC the original reason we did not take in a `Context` in the `Logger` interface was to push for implementations to not do something long-running because `Log` does block request completion currently. It also permits the `requestlog.Handler` implementation to log asynchronously in the future.

I'll throw in another couple of implementation ideas here:

1) Rather than having a field that stores a `Context`, have the field type be `interface { Value(interface{}) interface{} }` so as to disentangle the `Done` channel. This does unfortunately prevent future attempts at logging asynchronously and is a little awkward to use with APIs that access a `Context` (but can be worked around with struct embedding).
2) Add a method to `requestlog.Handler` like `SetContextTransform(f func(context.Context) interface{})` that invokes a callback to snapshot the data from the `Context` and then adds it to a new `interface{}` field in `Entry`. This would fit within the existing design goals while not running afoul of the `Context`-within-struct guidelines.

As an aside, migrating to OpenTelemetry would probably be a good idea to avoid users needing to deal with this in the common case. I believe OpenTelemetry is gaining more traction that OpenCensus did. I see this is already tracked as #2877.

**Comment by vangent** [comment]
I like @jba's suggestion; it's the most flexible. We can document the `Request` field with the caveats (don't touch `Body`, don't modify anything, and note that `Log` is synchronous so don't do anything long-running).

**Comment by mickeyreiss** [comment]
Thanks for the feedback, folks. Please take another look, as I've switched from `Context` to `Request`, added unit tests and deprecated the redundant fields with comments.

**Review by vangent — APPROVED** [review]

**Pull request merged**
