### PR TITLE
all: fix test breakage

### PR DESCRIPTION
**Pull request by ijt**

### CODE REVIEW

**Comment by ijt** [comment]
Fixes #610

**Comment by vangent** [comment]
Still failing....

#511 also seemed to have some unrelated changes like `.tf` files, so maybe better to revert it?

**Comment by ijt** [comment]
@vangent , good point. I'll re-create the PR to revert.

**Comment by ijt** [comment]
Created https://github.com/google/go-cloud/pull/612 to revert.

**Pull request closed without merging**
