### PR TITLE
mysql/rdsmysql: add OpenCensus configuration

### LINKED ISSUE #416: sql/ocsql: allow configuration of ocsql instrumentation
Currently `ocsql` is included with all trace options enabled. This means that sql queries and query parameters are annotated in spans, which can be undesirable from a security concern as well as a performance one (high cardinality annotations or heavily annotated spans do not sit well with all tracing backends in high QPS systems). This is why default `ocsql` is much more conservative and has all extra trace options disabled. 

I think it would be best to have the conservative default mirrored in Go cloud as well as the ability for consumers to set the configuration of `ocsql` when using Go cloud.

Happy to provide a PR if I can be guided a bit on how Go cloud wants configuration done (would this be part of rdsmysql.Params and cloudmysql.Params?)

### LINKED ISSUE #608: mysql: consider making an Options struct for all constructors
For example, for `mysql/cloudmysql`, the varargs `TraceOptions` could go in an `Options` struct, and leave us more flexibility for adding options later in a non-breaking way.

Something like:

```
type Options struct {
  traceOpts []ocsql.TraceOption  
}

func (o *options) TraceOptions(traceOpts ...ocsql.TraceOption) {
  o.traceOpts = traceOpts
}
```

Similarly for `rdsmysql`.

### PR DESCRIPTION
**Pull request by zombiezen**
Remove Options struct. Regenerated Guestbook Wire injectors.

Fixes #416
Fixes #608

### CODE REVIEW

**Comment by zombiezen** [comment]
@ijt, when you get the chance, can you please review?

**Comment by ijt** [comment]
The Params are supposed to be parameters for connecting to a db. Adding traceopts to this struct changes what it's about.

I don't feel strongly enough about this to block it though. Just my two cents.

**Comment by zombiezen** [comment]
> The Params are supposed to be parameters for connecting to a db. Adding traceopts to this struct changes what it's about.

This struct was added in #618. Since then, the consensus on #608 was that having the two structs was confusing. In #743, you performed the same operation this PR does but did not address this package. I am continuing the change for consistency. If you think this is the wrong decision, then we should discuss on #608.

> I don't feel strongly enough about this to block it though. Just my two cents.

I am blocked on having a firm resolution here, because I don't want to propagate further inconsistency as I introduce tracing into the PostgreSQL packages (#254).

**Comment by ijt** [comment]
Okay, let's keep it consistent. Sorry for the noise.

**Pull request merged**
