### PR TITLE
all: upgrade to Go 1.11

### PR DESCRIPTION
**Pull request by zombiezen**
Unblocks #380

### CODE REVIEW

**Comment by shantuo** [comment]
Do we want to drop testing for older version (1.10)?

**Comment by zombiezen** [comment]
If I understand you, are you saying we should also run a Travis job for Go 1.10? I'm not sure the complexity in the scripts (vgo versus go invocation) outweighs the benefit (support for a slightly less new Go standard library in a pre-1.0 library).

**Comment by shantuo** [comment]
Yes that would be tricky, originally I was thinking of just use `go` command instead of `vgo` for pre-1.10, but we do use some of the new commands.

**Comment by shantuo** [comment]
Is the Travis failure due to the module proxy?

**Comment by zombiezen** [comment]
No, it was due to a still-unknown issue with Wire + the `go` tool when modules are enabled. Added a TODO, and hoping that it will be addressed by #78.

**Pull request merged**
