### PR TITLE
using go.etcd.io/etcd for etcd import path

### PR DESCRIPTION
**Pull request by h8liu**
for #429

### CODE REVIEW

**Comment by h8liu** [comment]
interesting that your ci is using an internal GOPROXY? is it managed by your team?

**Comment by vangent** [comment]
> interesting that your ci is using an internal GOPROXY? is it managed by your team?

Yup.

**Comment by gyuho** [comment]
Hi, we are switching to go module in master branch soon. But, maybe not in release branches. Do you need us use go module for release branch as well?

**Comment by h8liu** [comment]
I do not really use your code, I am just seeing the build breakages from gopkgs.io. :)

it depends on if you want to support `go get` with go 1.10 and earlier in any flavor. their are cloud infra with CI/CD that are still staying behind using older go compiler versions. making master module only now is basically forcing your users to upgrade their entire setup to 1.11 (or vendor some older version).

Here is an example of another widely used library that starts using module but then force to revert back the import path change due to user's complaints:

https://github.com/pierrec/lz4/issues/33

**Comment by h8liu** [comment]
(I am actually not a member of go-cloud)

so quoting from:

https://github.com/etcd-io/etcd/issues/10083

> etcd is a binary program not a library. We have been talking about how to separate the client library versioning from the etcd binary versioning, but have not found a good way to do it.

I got this reply when I asked them to bump the version to 4.0.0 because import path change is not backward compatible. They refused because their version number is for the binary, not for the source code (client api). As a result, using release tags from the etcd git repo in go mod is probably incorrect.

**Comment by vangent** [comment]
Can we close this PR and revisit once etcd has done a new release with the new paths (whatever they end up tagging it)?

**Comment by h8liu** [comment]
sure, whatever.

again, no matter what version they use, it is not for go module import. the version is for the binary not the library.

**Pull request closed without merging**
