### PR TITLE
pubsub/azuresb: bump version from v0.7.0 to v0.8.0 for ServiceBus lib

### PR DESCRIPTION
**Pull request by devigned**
In github.com/Azure/azure-service-bus-go@v0.8.0 the method `ForeachKey` was removed in favor of `GetKeyValues` https://github.com/Azure/azure-service-bus-go/commit/46d69a5245927614c930e51b8eaf67923115f1a9#diff-b95c50d14ed7b4bb1cfecdc4e498d4dcL309.

This pull request will bump the dependency of Azure Service Bus to v0.8.0 and transitively azure-amqp-common-go/v2 and replace the `ForeachKey` call with `GetKeyValues`.

### CODE REVIEW

**Comment by vangent** [comment]
Hi @devigned , thanks for the contribution!

It looks like you'll need to run `./internal/testing/gomodcleanup.sh` to clean up the `go.mod/go.sum` files, and also run `go generate` in` internal/cmd/gocdk` to update the static assets for that CLI (one of the `go.mod` files you edited is compiled into that binary).

**Comment by vangent** [comment]
Sorry, looks like one more:
`./internal/testing/listdeps.sh > internal/testing/alldeps`.

**Comment by devigned** [comment]
@vangent, thank you for the help!

**Comment by vangent** [comment]
Thanks!

**Pull request merged**
